---
- name: "Network / IstioCtl / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ net_istioctl_application }}"
    sys_package_profiles: "{{ net_istioctl_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
