---
- name: "Network / IstioCtl / Prepare / Owners / Create"
  vars:
    sys_user:
      setup: true
    sys_user_accounts:
      - name: "{{ net_istioctl_owners['root']['user'] }}"
        group: "{{ net_istioctl_owners['root']['group'] }}"
        locked: false
        system: false
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_user"
...
