---
- name: "Network / Bind / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in net_bind_platforms

- name: "Network / Bind / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + net_bind_os_family + '.yml' }}"

- name: "Network / Bind / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "net_bind_prerequisite.yml"
  when:
    - net_bind['resolve_prereq'] is defined
    - net_bind['resolve_prereq']
...
