---
# Shared test variables
# test_user: "test_net_bind"
# test_group: "test_net_bind"
# test_home: "/home/test_net_bind"
# test_net_bind_setup_users:
#   - user: "{{ test_user }}"
#     home: "{{ test_home }}"
...
